[toolchain]
anchor_version = "0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
legasi_core = "4FW9iFaerNuX1GstRKSsWo9UfnTbjtqch3fEHkWMF1Uy"
legasi_flash = "Fj8CJNK1gBAuNR7dFbKLDckSstKmZn8ihTGwFXxfY93m"
legasi_gad = "89E84ALdDdGGNuJAxho2H45aC25kqNdGg7QtwTJ3pngK"
legasi_lending = "9356RoSbLTzWE55ab6GktcTocaNhPuBEDZvsmqjkCZYw"
legasi_leverage = "AVATHjGrdQ1KqtjHQ4gwRcuAYjwwScwgPsujLDpiA2g3"
legasi_lp = "CTwY4VSeueesSBc95G38X3WJYPriJEzyxjcCaZAc5LbY"

[programs.devnet]
legasi_core = "4FW9iFaerNuX1GstRKSsWo9UfnTbjtqch3fEHkWMF1Uy"
legasi_flash = "Fj8CJNK1gBAuNR7dFbKLDckSstKmZn8ihTGwFXxfY93m"
legasi_gad = "89E84ALdDdGGNuJAxho2H45aC25kqNdGg7QtwTJ3pngK"
legasi_lending = "9356RoSbLTzWE55ab6GktcTocaNhPuBEDZvsmqjkCZYw"
legasi_leverage = "AVATHjGrdQ1KqtjHQ4gwRcuAYjwwScwgPsujLDpiA2g3"
legasi_lp = "CTwY4VSeueesSBc95G38X3WJYPriJEzyxjcCaZAc5LbY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
